CREATE ROLE "TGBotSU" WITH
    LOGIN
    SUPERUSER
    CREATEDB
    CREATEROLE
    INHERIT
    REPLICATION
    CONNECTION LIMIT 3
    PASSWORD 'NDQ8ydV#';

CREATE DATABASE "TGBotDB"
    WITH
    OWNER = "TGbotSU"
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = 3
    IS_TEMPLATE = False;

CREATE SCHEMA "TGBotSchema"
    AUTHORIZATION "TGbotSU";